version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - LOG_LEVEL=debug
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  redis:
    image: "redis:alpine"
    container_name: "redis"
    expose:
        - "6379"
    ports:
        - '6379:6379'
